### ISSUE TITLE
[API] - Revisão do Código-Fonte e adição de validações

### ISSUE THREAD

**Issue by dannylo** [ifrn-pdcorp/sea#36]
- Revisar código-fonte para evitar vícios de codificação, padrões errados, e estruturas acopladas;

- Verificar se há validações a serem tratadas e tratá-las.

**Comment by dannylo** [comment]
O problema de um token JWT mal formado ou de uma assinatura inválida (para situações de tentativas maliciosas) foi tratado na classe de apoio ao autenticação. As exceptions são capturadas e o usuário é invalidado ao passar para o filtro, que deve retornar um 403 access denied.

`
			} catch (MalformedJwtException | SignatureException | UnsupportedJwtException ex){
				user = "";
			}`

As alterações foram feitas na issue 23 e submetidas via pull request para o master.

**Comment by dannylo** [comment]
Tratamento de requisições para imagens que não foram anteriormente carregadas (upload), a exception estava estourando no retorno da requisição, agora uma mensagem legível é retornada como resposta.

**Comment by WesleyDev01** [comment]
Problema referente a validação do formato de e-mail do usuário foi resolvido. As alterações foram feitas na issue wesley-validacoes.
